Repository TEENKIRI/TEENKIRI, pull requests merged in 2024-08, with the labels that each got.

#6 feat: Login/Register
  .idea/.gitignore
  .idea/JJAPMUPING.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  application.log
  sign_up/.idea/workspace.xml
  sign_up/teenkiri/teenkiri/.gitignore
  sign_up/teenkiri/teenkiri/application.log
  sign_up/teenkiri/teenkiri/application.log.2024-07-29.0.gz
  sign_up/teenkiri/teenkiri/build.gradle
  sign_up/teenkiri/teenkiri/gradle/wrapper/gradle-wrapper.jar
  sign_up/teenkiri/teenkiri/gradle/wrapper/gradle-wrapper.properties
  sign_up/teenkiri/teenkiri/gradlew
  sign_up/teenkiri/teenkiri/gradlew.bat
  sign_up/teenkiri/teenkiri/settings.gradle
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/Common/dto/CommonResDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/TeenkiriApplication.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/config/JwtAuthFilter.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/config/JwtTokenProvider.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/config/MailConfig.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/config/RedisConfig.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/config/SecurityConfig.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/controller/UserController.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/domain/User.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/EmailVerificationDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/PasswordResetDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/UserFindIdDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/UserFindPasswordDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/UserLoginDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/dto/UserSaveReqDto.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/repository/UserRepository.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/sevice/EmailService.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/sevice/RedisService.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/sevice/UserDetailServiceConfig.java
  sign_up/teenkiri/teenkiri/src/main/java/com/beyond/teenkiri/User/sevice/UserService.java
  sign_up/teenkiri/teenkiri/src/main/resources/templates/delete-account.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/find-id.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/find-password.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/login.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/login_0.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/register.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/reset-password.html
  sign_up/teenkiri/teenkiri/src/main/resources/templates/welcome.html
  sign_up/teenkiri/teenkiri/src/test/java/com/beyond/teenkiri/TeenkiriApplicationTests.java
Labels: 컨펌

#8 yohan's first commit
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/beyond/chat/ChatApplication.java
  src/main/java/com/beyond/chat/chatting/WebSocketConfig.java
  src/main/java/com/beyond/chat/chatting/controller/ChatController.java
  src/main/java/com/beyond/chat/chatting/domain/ChatMessage.java
  src/main/java/com/beyond/chat/chatting/repository/ChatMessageRepository.java
  src/main/java/com/beyond/chat/chatting/service/ChatService.java
  src/main/resources/application.yml
  src/main/resources/badwords.txt
  src/main/resources/static/css/chat.css
  src/main/resources/static/js/badWords.js
  src/main/resources/static/js/chat.js
  src/main/resources/templates/chat/index.html
  src/test/java/com/beyond/chat/BoardApplicationTests.java
Labels: 컨펌

#36 Feat:board
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  application.log
  application.log.2024-08-10.0.gz
  code/teenkiri/src/main/java/com/beyond/teenkiri/event/controller/EventController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/event/service/EventService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notice/controller/NoticeController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notice/service/NoticeService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/controller/PostController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/domain/Post.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostDetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostSaveReqDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostUpdateDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/service/PostService.java
  teenkiri_front/teenkiri_front/package-lock.json
  teenkiri_front/teenkiri_front/package.json
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/router/boardRouter.js
  teenkiri_front/teenkiri_front/src/router/index.js
  teenkiri_front/teenkiri_front/src/views/BoardCreate.vue
  teenkiri_front/teenkiri_front/src/views/BoardDetail.vue
  teenkiri_front/teenkiri_front/src/views/BoardList.vue
  teenkiri_front/teenkiri_front/src/views/BoardUpdate.vue
  teenkiri_front/teenkiri_front/src/views/UserCreate.vue
  teenkiri_front/teenkiri_front/src/views/UserList.vue
Labels: 컨펌

#39 fix: register address error
  code/teenkiri/src/main/java/com/beyond/teenkiri/TeenkiriApplication.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/config/JwtTokenprovider.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserService.java
  teenkiri_front/teenkiri_front/src/views/LoginPage.vue
  teenkiri_front/teenkiri_front/src/views/UserCreate.vue
Labels: 컨펌

#49 Feat/qna
  .idea/modules.xml
  application.log
  code/.idea/modules.xml
  code/.idea/modules/teenkiri.main.iml
  code/.idea/workspace.xml
  code/application.log
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/controller/CommentController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/domain/Comment.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/dto/CommentDetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/dto/CommentSaveReqDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/repository/CommentRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/service/CommentService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/event/service/EventService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/domain/Post.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostDetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostListResDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostSaveReqDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/service/PostService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/controller/QnAController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/domain/QnA.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnAAnswerReqDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnADetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/service/QnAService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/repository/UserRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserService.java
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/router/index.js
  teenkiri_front/teenkiri_front/src/router/memberRouter.js
  teenkiri_front/teenkiri_front/src/router/qnaRouter.js
  teenkiri_front/teenkiri_front/src/views/board/BoardDetail.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardList.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateAnswer.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
  teenkiri_front/teenkiri_front/src/views/user/UpdateUserInfo.vue
Labels: 컨펌

#51 FE_boardAndQnA
  application.log
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/domain/Post.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/post/dto/PostDetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/service/QnAService.java
  teenkiri_front/teenkiri_front/src/views/board/BoardCreate.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardDetail.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardList.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardUpdate.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateAnswer.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/UpdateAnswer.vue
  teenkiri_front/teenkiri_front/src/views/qna/UpdateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/user/UpdateUserInfo.vue
  teenkiri_front/teenkiri_front/vue.config.js
Labels: merge

#54 feat : subject Detail 진행 중, QnA 및 Review 프레임 제작
  code/teenkiri/src/main/java/com/beyond/teenkiri/lecture/controller/LectureController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/lecture/domain/Lecture.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/lecture/dto/LectureListResDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/config/SecurityConfig.java
  teenkiri_front/teenkiri_front/src/components/subject/SubjectDetailComponent.vue
  teenkiri_front/teenkiri_front/src/router/subjectRouter.js
  teenkiri_front/teenkiri_front/src/views/subject/SubjectDetail.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectQna.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectReview.vue
Labels: merge

#59 feat : login 유저 정보(토큰, 아이디, 이메일) 불러오는 store 기능 추가, lecture detail 기능 진행 중
  teenkiri_front/teenkiri_front/src/main.js
  teenkiri_front/teenkiri_front/src/router/subjectRouter.js
  teenkiri_front/teenkiri_front/src/store/index.js
  teenkiri_front/teenkiri_front/src/store/user.js
  teenkiri_front/teenkiri_front/src/views/lecture/LectureDetail.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectDetail.vue
  teenkiri_front/teenkiri_front/src/views/user/LoginPage.vue
Labels: merge

#63 feat : 강좌 및 강의 상세페이지, 유저별 진행률 기능 진행 중
  application.log
  code/teenkiri/src/main/java/com/beyond/teenkiri/enrollment/repository/EnrollmentRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/lecture/service/LectureService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserSubjectService.java
  teenkiri_front/teenkiri_front/package-lock.json
  teenkiri_front/teenkiri_front/package.json
  teenkiri_front/teenkiri_front/src/components/Lecture/videoPlayer.vue
  teenkiri_front/teenkiri_front/src/main.js
  teenkiri_front/teenkiri_front/src/views/lecture/LectureDetail.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectList.vue
Labels: merge

#64 Fe/report list
  code/teenkiri/application.log.2024-08-16.0.gz
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/domain/QnA.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnADetailDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnAListResDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnASaveReqDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/service/QnAService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/config/JwtAuthFilter.java
  teenkiri_front/teenkiri_front/src/router/index.js
  teenkiri_front/teenkiri_front/src/router/reportRouter.js
  teenkiri_front/teenkiri_front/src/views/qna/CreateAnswer.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
  teenkiri_front/teenkiri_front/src/views/qna/UpdateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/report/ReportList.vue
Labels: merge

#65 Fe/subject qna
  code/teenkiri/src/main/java/com/beyond/teenkiri/comment/service/CommentService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationListDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/controller/QnAController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/domain/QnA.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/dto/QnAListResDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/repository/QnARepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/service/QnAService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/report/service/ReportService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/repository/UserRepository.java
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/router/boardRouter.js
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
  teenkiri_front/teenkiri_front/src/views/report/ReportCreate.vue
  teenkiri_front/teenkiri_front/src/views/report/ReportList.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectQna.vue
Labels: merge

#67 feat : 강의페이지 시청페이지 작업, progress바 추가
  teenkiri_front/teenkiri_front/src/components/Lecture/videoPlayer.vue
  teenkiri_front/teenkiri_front/src/views/lecture/LectureDetail.vue
Labels: merge

#68 Fe/etc
  code/teenkiri/application.log.2024-08-17.0.gz
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/controller/QnAController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/repository/QnARepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/qna/service/QnAService.java
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectQna.vue
Labels: 컨펌, merge

#69 feat : 강좌 상세페이지 및 강좌추천 기능 수정 및 추가
  code/teenkiri/src/main/java/com/beyond/teenkiri/subject/domain/Subject.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/subject/dto/SubjectDetResDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/subject/service/SubjectService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserSubjectService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/wish/repository/WishRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/wish/service/WishService.java
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/components/subject/SubjectDetailComponent.vue
  teenkiri_front/teenkiri_front/src/router/subjectRouter.js
  teenkiri_front/teenkiri_front/src/views/subject/SubjectDetail.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectRecommendList.vue
Labels: merge

#70 Fe/etc
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationListDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/service/NotificationService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/controller/UserController.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/user/service/UserService.java
  teenkiri_front/teenkiri_front/src/components/AppSidebar.vue
  teenkiri_front/teenkiri_front/src/router/memberRouter.js
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
  teenkiri_front/teenkiri_front/src/views/qna/UserQuestions.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectQna.vue
  teenkiri_front/teenkiri_front/src/views/user/UpdateUserInfo.vue
  teenkiri_front/teenkiri_front/src/views/user/UserNotificaion.vue
  teenkiri_front/teenkiri_front/src/views/user/myQnAListPage.vue
Labels: merge

#71 Fe/etc
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/dto/NotificationListDto.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/repository/NotificationRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/notification/service/NotificationService.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/review/repository/ReviewRepository.java
  code/teenkiri/src/main/java/com/beyond/teenkiri/review/service/ReviewService.java
  teenkiri_front/teenkiri_front/src/components/HeaderComponent.vue
  teenkiri_front/teenkiri_front/src/components/subject/SubjectDetailComponent.vue
  teenkiri_front/teenkiri_front/src/router/subjectRouter.js
  teenkiri_front/teenkiri_front/src/views/board/BoardCreate.vue
  teenkiri_front/teenkiri_front/src/views/qna/CreateQuestion.vue
  teenkiri_front/teenkiri_front/src/views/qna/UserQuestions.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectDetail.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectQna.vue
  teenkiri_front/teenkiri_front/src/views/subject/SubjectReview.vue
  teenkiri_front/teenkiri_front/src/views/user/UserNotificaion.vue
Labels: merge

#82 view: 게시판 및 QnA 디자인 수정 및 권한 관리
  teenkiri_front/teenkiri_front/src/views/board/BoardDetail.vue
  teenkiri_front/teenkiri_front/src/views/board/BoardList.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaDetail.vue
  teenkiri_front/teenkiri_front/src/views/qna/QnaList.vue
Labels: merge
